const VEHICULOS = [
  // ===== TOYOTA (8) =====
  {
    id: 1,
    marca: "Toyota",
    modelo: "RAV4",
    ano: 2024,
    tipo: "SUV",
    precio: 2850000,
    precioConsultar: false,
    combustible: "Gasolina",
    transmision: "Automatica",
    kilometraje: 0,
    color: "Blanco Perla",
    imagenes: [
      "https://images.unsplash.com/photo-1583121274602-3e2820c69888?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1544636331-e26879cd4d9b?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=800&q=80"
    ],
    destacado: true,
    condicion: "Nuevo",
    descripcion: "Toyota RAV4 2024 nueva con todas las opciones de serie, ideal para la familia dominicana.",
    caracteristicas: ["Camara de reversa", "Pantalla tactil 8 pulgadas", "Control de crucero", "Sensores de estacionamiento", "Bluetooth"],
    fechaAgregado: "2026-03-15",
    enOferta: false,
    precioAnterior: null
  },
  {
    id: 2,
    marca: "Toyota",
    modelo: "Corolla",
    ano: 2025,
    tipo: "Sedan",
    precio: 1750000,
    precioConsultar: false,
    combustible: "Gasolina",
    transmision: "Automatica",
    kilometraje: 0,
    color: "Gris Oscuro",
    imagenes: [
      "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=800&q=80"
    ],
    destacado: false,
    condicion: "Nuevo",
    descripcion: "El sedan mas vendido del mundo, ahora con diseno renovado y mayor eficiencia en combustible.",
    caracteristicas: ["Toyota Safety Sense", "Android Auto y Apple CarPlay", "Asientos en tela premium", "Aire acondicionado dual"],
    fechaAgregado: "2026-02-20",
    enOferta: true,
    precioAnterior: 1950000
  },
  {
    id: 3,
    marca: "Toyota",
    modelo: "Hilux",
    ano: 2023,
    tipo: "Pickup",
    precio: 2650000,
    precioConsultar: false,
    combustible: "Diesel",
    transmision: "Automatica",
    kilometraje: 35000,
    color: "Negro",
    imagenes: [
      "https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1606016159991-dfe4f2746ad5?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1559416523-140ddc3d238c?auto=format&fit=crop&w=800&q=80"
    ],
    destacado: false,
    condicion: "Usado",
    descripcion: "Toyota Hilux turbo diesel en excelentes condiciones, perfecta para trabajo y aventura.",
    caracteristicas: ["Traccion 4x4", "Motor turbo diesel 2.8L", "Cama de carga reforzada", "Diferencial trasero con bloqueo", "Barras de techo"],
    fechaAgregado: "2026-01-10",
    enOferta: false,
    precioAnterior: null
  },
  {
    id: 4,
    marca: "Toyota",
    modelo: "Fortuner",
    ano: 2024,
    tipo: "SUV",
    precio: 3450000,
    precioConsultar: false,
    combustible: "Diesel",
    transmision: "Automatica",
    kilometraje: 12000,
    color: "Plata",
    imagenes: [
      "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1619405399517-d7fce0f13302?auto=format&fit=crop&w=800&q=80"
    ],
    destacado: true,
    condicion: "Usado",
    descripcion: "Fortuner con poco recorrido, lista para dominar cualquier terreno de la isla.",
    caracteristicas: ["7 asientos", "Traccion 4x4", "Control de descenso", "Pantalla multimedia", "Camara 360 grados"],
    fechaAgregado: "2026-03-01",
    enOferta: false,
    precioAnterior: null
  },
  {
    id: 5,
    marca: "Toyota",
    modelo: "Land Cruiser Prado",
    ano: 2022,
    tipo: "SUV",
    precio: 4200000,
    precioConsultar: false,
    combustible: "Diesel",
    transmision: "Automatica",
    kilometraje: 45000,
    color: "Verde Oscuro",
    imagenes: [
      "https://images.unsplash.com/photo-1629897048514-3dd7414fe72a?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1619767886558-efdc259cde1a?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1609521263047-f8f205293f24?auto=format&fit=crop&w=800&q=80"
    ],
    destacado: false,
    condicion: "Usado",
    descripcion: "Land Cruiser Prado con historial de mantenimiento completo, robusta y confiable.",
    caracteristicas: ["Motor diesel 2.8L turbo", "Asientos en cuero", "Sistema KDSS", "Techo corredizo", "Sistema de navegacion"],
    fechaAgregado: "2025-11-28",
    enOferta: false,
    precioAnterior: null
  },
  {
    id: 6,
    marca: "Toyota",
    modelo: "Yaris",
    ano: 2023,
    tipo: "Sedan",
    precio: 1150000,
    precioConsultar: false,
    combustible: "Gasolina",
    transmision: "Automatica",
    kilometraje: 22000,
    color: "Rojo",
    imagenes: [
      "https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?auto=format&fit=crop&w=800&q=80"
    ],
    destacado: false,
    condicion: "Usado",
    descripcion: "Yaris economico y practico, ideal para el transito de Santo Domingo y ciudades del sur.",
    caracteristicas: ["Bajo consumo de combustible", "Aire acondicionado", "Direccion asistida electrica", "Vidrios electricos"],
    fechaAgregado: "2025-09-14",
    enOferta: false,
    precioAnterior: null
  },
  {
    id: 7,
    marca: "Toyota",
    modelo: "Camry",
    ano: 2024,
    tipo: "Sedan",
    precio: 2600000,
    precioConsultar: false,
    combustible: "Hibrido",
    transmision: "Automatica",
    kilometraje: 0,
    color: "Azul Metalico",
    imagenes: [
      "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1616422285623-13ff0162193c?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1617469767053-d3b523a0b982?auto=format&fit=crop&w=800&q=80"
    ],
    destacado: false,
    condicion: "Nuevo",
    descripcion: "Camry hibrido con tecnologia de punta, maxima eficiencia y confort de lujo.",
    caracteristicas: ["Motor hibrido", "Asientos en cuero", "JBL Premium Audio", "Carga inalambrica", "Head-up display"],
    fechaAgregado: "2026-03-20",
    enOferta: false,
    precioAnterior: null
  },
  {
    id: 8,
    marca: "Toyota",
    modelo: "4Runner",
    ano: 2021,
    tipo: "SUV",
    precio: 3100000,
    precioConsultar: false,
    combustible: "Gasolina",
    transmision: "Automatica",
    kilometraje: 68000,
    color: "Blanco",
    imagenes: [
      "https://images.unsplash.com/photo-1550355291-bbee04a92027?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1583121274602-3e2820c69888?auto=format&fit=crop&w=800&q=80"
    ],
    destacado: false,
    condicion: "Usado",
    descripcion: "4Runner reconocida por su durabilidad todoterreno, lista para aventuras en la republica.",
    caracteristicas: ["Motor V6 4.0L", "Traccion 4x4 permanente", "Sistema Crawl Control", "Suspension reforzada", "Capacidad de remolque"],
    fechaAgregado: "2025-12-05",
    enOferta: false,
    precioAnterior: null
  },

  // ===== HONDA (7) =====
  {
    id: 9,
    marca: "Honda",
    modelo: "CR-V",
    ano: 2024,
    tipo: "SUV",
    precio: 2750000,
    precioConsultar: false,
    combustible: "Gasolina",
    transmision: "Automatica",
    kilometraje: 8000,
    color: "Gris Plata",
    imagenes: [
      "https://images.unsplash.com/photo-1544636331-e26879cd4d9b?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=800&q=80"
    ],
    destacado: true,
    condicion: "Usado",
    descripcion: "Honda CR-V practicamente nueva, amplia y comoda para toda la familia.",
    caracteristicas: ["Honda Sensing", "Pantalla tactil 9 pulgadas", "Asientos calefactados", "Techo panoramico", "Llave inteligente"],
    fechaAgregado: "2026-02-28",
    enOferta: false,
    precioAnterior: null
  },
  {
    id: 10,
    marca: "Honda",
    modelo: "Civic",
    ano: 2025,
    tipo: "Sedan",
    precio: 1850000,
    precioConsultar: false,
    combustible: "Gasolina",
    transmision: "Automatica",
    kilometraje: 0,
    color: "Negro",
    imagenes: [
      "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&w=800&q=80"
    ],
    destacado: false,
    condicion: "Nuevo",
    descripcion: "Civic de nueva generacion con diseno deportivo y la confiabilidad que caracteriza a Honda.",
    caracteristicas: ["Motor turbo 1.5L", "Bose Premium Audio", "Apple CarPlay inalambrico", "Faros LED adaptativos"],
    fechaAgregado: "2026-03-10",
    enOferta: false,
    precioAnterior: null
  },
  {
    id: 11,
    marca: "Honda",
    modelo: "Accord",
    ano: 2023,
    tipo: "Sedan",
    precio: 2200000,
    precioConsultar: false,
    combustible: "Hibrido",
    transmision: "Automatica",
    kilometraje: 30000,
    color: "Azul Acero",
    imagenes: [
      "https://images.unsplash.com/photo-1606016159991-dfe4f2746ad5?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1559416523-140ddc3d238c?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?auto=format&fit=crop&w=800&q=80"
    ],
    destacado: false,
    condicion: "Usado",
    descripcion: "Accord hibrido con excelente economia de combustible y acabados premium.",
    caracteristicas: ["Motor hibrido e:HEV", "Asientos en cuero", "Wireless CarPlay", "Camara multi-angulo", "Control de clima dual"],
    fechaAgregado: "2025-10-22",
    enOferta: false,
    precioAnterior: null
  },
  {
    id: 12,
    marca: "Honda",
    modelo: "HR-V",
    ano: 2024,
    tipo: "Crossover",
    precio: 1950000,
    precioConsultar: false,
    combustible: "Gasolina",
    transmision: "Automatica",
    kilometraje: 0,
    color: "Rojo Metalico",
    imagenes: [
      "https://images.unsplash.com/photo-1619405399517-d7fce0f13302?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1629897048514-3dd7414fe72a?auto=format&fit=crop&w=800&q=80"
    ],
    destacado: false,
    condicion: "Nuevo",
    descripcion: "HR-V compacta pero espaciosa, perfecta para moverse por la ciudad con estilo.",
    caracteristicas: ["Asientos magicos Honda", "Pantalla tactil 7 pulgadas", "Camara de reversa", "Honda Connect"],
    fechaAgregado: "2026-01-18",
    enOferta: false,
    precioAnterior: null
  },
  {
    id: 13,
    marca: "Honda",
    modelo: "Pilot",
    ano: 2023,
    tipo: "SUV",
    precio: 3600000,
    precioConsultar: false,
    combustible: "Gasolina",
    transmision: "Automatica",
    kilometraje: 25000,
    color: "Blanco Diamante",
    imagenes: [
      "https://images.unsplash.com/photo-1619767886558-efdc259cde1a?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1609521263047-f8f205293f24?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?auto=format&fit=crop&w=800&q=80"
    ],
    destacado: false,
    condicion: "Usado",
    descripcion: "Pilot con 3 filas de asientos, perfecta para familias grandes que necesitan espacio.",
    caracteristicas: ["8 asientos", "Motor V6 3.5L", "Traccion AWD", "Sistema de entretenimiento trasero", "Portaequipaje amplio"],
    fechaAgregado: "2025-08-30",
    enOferta: false,
    precioAnterior: null
  },
  {
    id: 14,
    marca: "Honda",
    modelo: "City",
    ano: 2023,
    tipo: "Sedan",
    precio: 1100000,
    precioConsultar: false,
    combustible: "Gasolina",
    transmision: "Automatica",
    kilometraje: 18000,
    color: "Plata",
    imagenes: [
      "https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=800&q=80"
    ],
    destacado: false,
    condicion: "Usado",
    descripcion: "Honda City compacto y eficiente, bajo costo de mantenimiento y gran valor de reventa.",
    caracteristicas: ["Motor i-VTEC 1.5L", "Pantalla multimedia", "Aire acondicionado", "Frenos ABS con EBD"],
    fechaAgregado: "2025-07-12",
    enOferta: false,
    precioAnterior: null
  },
  {
    id: 15,
    marca: "Honda",
    modelo: "Fit",
    ano: 2022,
    tipo: "Sedan",
    precio: 950000,
    precioConsultar: false,
    combustible: "Gasolina",
    transmision: "Automatica",
    kilometraje: 42000,
    color: "Amarillo",
    imagenes: [
      "https://images.unsplash.com/photo-1616422285623-13ff0162193c?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1617469767053-d3b523a0b982?auto=format&fit=crop&w=800&q=80"
    ],
    destacado: false,
    condicion: "Usado",
    descripcion: "Fit versatil y economico, sorprende por su espacio interior a pesar de su tamano compacto.",
    caracteristicas: ["Asientos ultra plegables", "Bajo consumo de combustible", "Bluetooth", "Vidrios electricos"],
    fechaAgregado: "2025-06-05",
    enOferta: false,
    precioAnterior: null
  },

  // ===== HYUNDAI (7) =====
  {
    id: 16,
    marca: "Hyundai",
    modelo: "Tucson",
    ano: 2025,
    tipo: "SUV",
    precio: 2450000,
    precioConsultar: false,
    combustible: "Gasolina",
    transmision: "Automatica",
    kilometraje: 0,
    color: "Gris Amazonas",
    imagenes: [
      "https://images.unsplash.com/photo-1550355291-bbee04a92027?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1583121274602-3e2820c69888?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1544636331-e26879cd4d9b?auto=format&fit=crop&w=800&q=80"
    ],
    destacado: true,
    condicion: "Nuevo",
    descripcion: "Tucson con diseno futurista y tecnologia avanzada, la SUV mas popular del Caribe.",
    caracteristicas: ["Hyundai SmartSense", "Pantalla dual 10.25 pulgadas", "Carga inalambrica", "Llave digital", "Techo panoramico"],
    fechaAgregado: "2026-03-25",
    enOferta: true,
    precioAnterior: 2750000
  },
  {
    id: 17,
    marca: "Hyundai",
    modelo: "Elantra",
    ano: 2024,
    tipo: "Sedan",
    precio: 1550000,
    precioConsultar: false,
    combustible: "Gasolina",
    transmision: "Automatica",
    kilometraje: 15000,
    color: "Blanco",
    imagenes: [
      "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=800&q=80"
    ],
    destacado: false,
    condicion: "Usado",
    descripcion: "Elantra con lineas angulares y excelente equipamiento de serie para su segmento.",
    caracteristicas: ["Pantalla tactil 8 pulgadas", "Apple CarPlay y Android Auto", "Faros LED", "6 airbags"],
    fechaAgregado: "2026-01-05",
    enOferta: false,
    precioAnterior: null
  },
  {
    id: 18,
    marca: "Hyundai",
    modelo: "Santa Fe",
    ano: 2023,
    tipo: "SUV",
    precio: 3200000,
    precioConsultar: false,
    combustible: "Diesel",
    transmision: "Automatica",
    kilometraje: 38000,
    color: "Negro Nocturno",
    imagenes: [
      "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1606016159991-dfe4f2746ad5?auto=format&fit=crop&w=800&q=80"
    ],
    destacado: false,
    condicion: "Usado",
    descripcion: "Santa Fe diesel con gran capacidad de carga y traccion integral para cualquier camino.",
    caracteristicas: ["Motor diesel 2.2L CRDi", "Traccion AWD HTRAC", "7 asientos", "Camara de vision 360", "Control de crucero adaptativo"],
    fechaAgregado: "2025-10-15",
    enOferta: false,
    precioAnterior: null
  },
  {
    id: 19,
    marca: "Hyundai",
    modelo: "Creta",
    ano: 2025,
    tipo: "Crossover",
    precio: 1650000,
    precioConsultar: false,
    combustible: "Gasolina",
    transmision: "Automatica",
    kilometraje: 0,
    color: "Azul Denim",
    imagenes: [
      "https://images.unsplash.com/photo-1559416523-140ddc3d238c?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?auto=format&fit=crop&w=800&q=80"
    ],
    destacado: false,
    condicion: "Nuevo",
    descripcion: "Creta nueva con un diseno atractivo y el mejor precio en su categoria.",
    caracteristicas: ["Pantalla multimedia 10.25 pulgadas", "Camara de reversa", "Sensor de estacionamiento", "Bluetooth y USB"],
    fechaAgregado: "2026-02-14",
    enOferta: false,
    precioAnterior: null
  },
  {
    id: 20,
    marca: "Hyundai",
    modelo: "Accent",
    ano: 2022,
    tipo: "Sedan",
    precio: 1050000,
    precioConsultar: false,
    combustible: "Gasolina",
    transmision: "Manual",
    kilometraje: 55000,
    color: "Gris",
    imagenes: [
      "https://images.unsplash.com/photo-1619405399517-d7fce0f13302?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1629897048514-3dd7414fe72a?auto=format&fit=crop&w=800&q=80"
    ],
    destacado: false,
    condicion: "Usado",
    descripcion: "Accent economico con transmision manual, excelente opcion para primer vehiculo.",
    caracteristicas: ["Motor 1.4L eficiente", "Aire acondicionado", "Radio con Bluetooth", "Direccion asistida"],
    fechaAgregado: "2025-05-20",
    enOferta: false,
    precioAnterior: null
  },
  {
    id: 21,
    marca: "Hyundai",
    modelo: "Sonata",
    ano: 2024,
    tipo: "Sedan",
    precio: 2350000,
    precioConsultar: false,
    combustible: "Gasolina",
    transmision: "Automatica",
    kilometraje: 10000,
    color: "Blanco Quartz",
    imagenes: [
      "https://images.unsplash.com/photo-1619767886558-efdc259cde1a?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1609521263047-f8f205293f24?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?auto=format&fit=crop&w=800&q=80"
    ],
    destacado: false,
    condicion: "Usado",
    descripcion: "Sonata elegante con motor turbo y acabados de nivel premium a precio accesible.",
    caracteristicas: ["Motor Smartstream turbo 1.6L", "Asientos ventilados", "Pantalla digital 12.3 pulgadas", "Modo de conduccion Sport", "Faros LED parametricos"],
    fechaAgregado: "2026-03-02",
    enOferta: false,
    precioAnterior: null
  },
  {
    id: 22,
    marca: "Hyundai",
    modelo: "Kona",
    ano: 2025,
    tipo: "Crossover",
    precio: 1800000,
    precioConsultar: false,
    combustible: "Gasolina",
    transmision: "Automatica",
    kilometraje: 0,
    color: "Verde Oliva",
    imagenes: [
      "https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=800&q=80"
    ],
    destacado: false,
    condicion: "Nuevo",
    descripcion: "Kona completamente rediseñada con personalidad unica y tecnologia de vanguardia.",
    caracteristicas: ["Diseno bicolor", "Pantalla panoramica", "Hyundai SmartSense", "Modo de manejo seleccionable"],
    fechaAgregado: "2026-03-18",
    enOferta: false,
    precioAnterior: null
  },

  // ===== KIA (6) =====
  {
    id: 23,
    marca: "Kia",
    modelo: "Sportage",
    ano: 2025,
    tipo: "SUV",
    precio: 2500000,
    precioConsultar: false,
    combustible: "Gasolina",
    transmision: "Automatica",
    kilometraje: 0,
    color: "Gris Mineral",
    imagenes: [
      "https://images.unsplash.com/photo-1616422285623-13ff0162193c?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1617469767053-d3b523a0b982?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1550355291-bbee04a92027?auto=format&fit=crop&w=800&q=80"
    ],
    destacado: false,
    condicion: "Nuevo",
    descripcion: "Sportage con diseno vanguardista y la mejor garantia del mercado dominicano.",
    caracteristicas: ["Pantalla curva dual", "ADAS nivel 2", "Asientos en cuero sintetico", "Cargador inalambrico Qi", "7 anos de garantia"],
    fechaAgregado: "2026-02-10",
    enOferta: false,
    precioAnterior: null
  },
  {
    id: 24,
    marca: "Kia",
    modelo: "K5",
    ano: 2024,
    tipo: "Sedan",
    precio: 2100000,
    precioConsultar: false,
    combustible: "Gasolina",
    transmision: "Automatica",
    kilometraje: 20000,
    color: "Rojo Pasion",
    imagenes: [
      "https://images.unsplash.com/photo-1583121274602-3e2820c69888?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1544636331-e26879cd4d9b?auto=format&fit=crop&w=800&q=80"
    ],
    destacado: false,
    condicion: "Usado",
    descripcion: "K5 deportivo y elegante, el sedan que combina rendimiento con sofisticacion.",
    caracteristicas: ["Motor turbo 1.6L", "Interior bicolor", "Pantalla 10.25 pulgadas", "Modos de conduccion"],
    fechaAgregado: "2025-12-20",
    enOferta: false,
    precioAnterior: null
  },
  {
    id: 25,
    marca: "Kia",
    modelo: "Seltos",
    ano: 2024,
    tipo: "Crossover",
    precio: 1700000,
    precioConsultar: false,
    combustible: "Gasolina",
    transmision: "Automatica",
    kilometraje: 0,
    color: "Naranja Stonic",
    imagenes: [
      "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=800&q=80"
    ],
    destacado: false,
    condicion: "Nuevo",
    descripcion: "Seltos con estilo juvenil y gran equipamiento para conquistar las calles.",
    caracteristicas: ["Sound Mood Lighting", "UVO Connect", "Camara de reversa", "Control de estabilidad", "Faros LED"],
    fechaAgregado: "2026-01-25",
    enOferta: false,
    precioAnterior: null
  },
  {
    id: 26,
    marca: "Kia",
    modelo: "Sorento",
    ano: 2023,
    tipo: "SUV",
    precio: 3100000,
    precioConsultar: false,
    combustible: "Diesel",
    transmision: "Automatica",
    kilometraje: 32000,
    color: "Negro",
    imagenes: [
      "https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1606016159991-dfe4f2746ad5?auto=format&fit=crop&w=800&q=80"
    ],
    destacado: false,
    condicion: "Usado",
    descripcion: "Sorento diesel con 7 asientos, la SUV familiar por excelencia con capacidad todoterreno.",
    caracteristicas: ["Motor diesel 2.2L", "7 asientos", "Traccion AWD", "Frenos Brembo", "Sistema Harman Kardon"],
    fechaAgregado: "2025-11-10",
    enOferta: false,
    precioAnterior: null
  },
  {
    id: 27,
    marca: "Kia",
    modelo: "Forte",
    ano: 2023,
    tipo: "Sedan",
    precio: 1350000,
    precioConsultar: false,
    combustible: "Gasolina",
    transmision: "Automatica",
    kilometraje: 28000,
    color: "Plata",
    imagenes: [
      "https://images.unsplash.com/photo-1559416523-140ddc3d238c?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?auto=format&fit=crop&w=800&q=80"
    ],
    destacado: false,
    condicion: "Usado",
    descripcion: "Forte confiable y bien equipado, excelente relacion precio-calidad en sedan compacto.",
    caracteristicas: ["Motor 2.0L MPI", "Transmision IVT", "Apple CarPlay", "Frenado autonomo de emergencia"],
    fechaAgregado: "2025-09-28",
    enOferta: false,
    precioAnterior: null
  },
  {
    id: 28,
    marca: "Kia",
    modelo: "Rio",
    ano: 2022,
    tipo: "Sedan",
    precio: 980000,
    precioConsultar: false,
    combustible: "Gasolina",
    transmision: "Manual",
    kilometraje: 48000,
    color: "Azul",
    imagenes: [
      "https://images.unsplash.com/photo-1619405399517-d7fce0f13302?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1629897048514-3dd7414fe72a?auto=format&fit=crop&w=800&q=80"
    ],
    destacado: false,
    condicion: "Usado",
    descripcion: "Rio subcompacto con bajo consumo, excelente para uso diario y facil de estacionar.",
    caracteristicas: ["Motor Gamma 1.4L", "Aire acondicionado", "Bluetooth", "Direccion electroasistida"],
    fechaAgregado: "2025-04-15",
    enOferta: false,
    precioAnterior: null
  },

  // ===== NISSAN (6) =====
  {
    id: 29,
    marca: "Nissan",
    modelo: "X-Trail",
    ano: 2024,
    tipo: "SUV",
    precio: 2700000,
    precioConsultar: false,
    combustible: "Gasolina",
    transmision: "Automatica",
    kilometraje: 5000,
    color: "Champagne",
    imagenes: [
      "https://images.unsplash.com/photo-1619767886558-efdc259cde1a?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1609521263047-f8f205293f24?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?auto=format&fit=crop&w=800&q=80"
    ],
    destacado: false,
    condicion: "Usado",
    descripcion: "X-Trail con tecnologia e-POWER y espacio para toda la familia con comodidad.",
    caracteristicas: ["ProPILOT Assist", "Pantalla 12.3 pulgadas", "Asientos Zero Gravity", "Around View Monitor", "Techo panoramico"],
    fechaAgregado: "2026-02-05",
    enOferta: false,
    precioAnterior: null
  },
  {
    id: 30,
    marca: "Nissan",
    modelo: "Sentra",
    ano: 2024,
    tipo: "Sedan",
    precio: 1500000,
    precioConsultar: false,
    combustible: "Gasolina",
    transmision: "Automatica",
    kilometraje: 0,
    color: "Blanco Perla",
    imagenes: [
      "https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=800&q=80"
    ],
    destacado: false,
    condicion: "Nuevo",
    descripcion: "Sentra completamente renovado con una presencia elegante y equipamiento de primer nivel.",
    caracteristicas: ["Nissan Safety Shield 360", "Pantalla flotante 8 pulgadas", "Motor 2.0L", "Camara de reversa inteligente"],
    fechaAgregado: "2026-03-12",
    enOferta: true,
    precioAnterior: 1700000
  },
  {
    id: 31,
    marca: "Nissan",
    modelo: "Frontier",
    ano: 2023,
    tipo: "Pickup",
    precio: 2900000,
    precioConsultar: false,
    combustible: "Diesel",
    transmision: "Automatica",
    kilometraje: 40000,
    color: "Rojo Lava",
    imagenes: [
      "https://images.unsplash.com/photo-1616422285623-13ff0162193c?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1617469767053-d3b523a0b982?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1550355291-bbee04a92027?auto=format&fit=crop&w=800&q=80"
    ],
    destacado: false,
    condicion: "Usado",
    descripcion: "Frontier robusta y potente, disenada para el trabajo duro y los caminos dificiles.",
    caracteristicas: ["Motor diesel 2.3L biturbo", "Traccion 4x4", "Hill Start Assist", "Caja de carga con recubrimiento", "Gancho de remolque"],
    fechaAgregado: "2025-08-18",
    enOferta: false,
    precioAnterior: null
  },
  {
    id: 32,
    marca: "Nissan",
    modelo: "Kicks",
    ano: 2025,
    tipo: "Crossover",
    precio: 1600000,
    precioConsultar: false,
    combustible: "Gasolina",
    transmision: "Automatica",
    kilometraje: 0,
    color: "Naranja",
    imagenes: [
      "https://images.unsplash.com/photo-1583121274602-3e2820c69888?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1544636331-e26879cd4d9b?auto=format&fit=crop&w=800&q=80"
    ],
    destacado: false,
    condicion: "Nuevo",
    descripcion: "Kicks con diseno audaz y colores vibrantes, el crossover urbano mas divertido.",
    caracteristicas: ["Techo flotante bicolor", "Bose Personal Plus Audio", "Monitor de punto ciego", "Android Auto y Apple CarPlay"],
    fechaAgregado: "2026-03-08",
    enOferta: false,
    precioAnterior: null
  },
  {
    id: 33,
    marca: "Nissan",
    modelo: "Versa",
    ano: 2023,
    tipo: "Sedan",
    precio: 1050000,
    precioConsultar: false,
    combustible: "Gasolina",
    transmision: "Automatica",
    kilometraje: 35000,
    color: "Gris Oxford",
    imagenes: [
      "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=800&q=80"
    ],
    destacado: false,
    condicion: "Usado",
    descripcion: "Versa espacioso y accesible, uno de los sedanes mas vendidos en Republica Dominicana.",
    caracteristicas: ["Motor HR16DE 1.6L", "Transmision Xtronic CVT", "Apple CarPlay", "Alerta de colision frontal"],
    fechaAgregado: "2025-07-22",
    enOferta: false,
    precioAnterior: null
  },
  {
    id: 34,
    marca: "Nissan",
    modelo: "Pathfinder",
    ano: 2022,
    tipo: "SUV",
    precio: 3350000,
    precioConsultar: false,
    combustible: "Gasolina",
    transmision: "Automatica",
    kilometraje: 52000,
    color: "Bronce Metalico",
    imagenes: [
      "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1606016159991-dfe4f2746ad5?auto=format&fit=crop&w=800&q=80"
    ],
    destacado: false,
    condicion: "Usado",
    descripcion: "Pathfinder con motor V6 y capacidad para 8 pasajeros, aventura sin limites.",
    caracteristicas: ["Motor V6 3.5L 284 HP", "8 pasajeros", "Transmision de 9 velocidades", "7 modos de conduccion", "Remolque hasta 6,000 lbs"],
    fechaAgregado: "2025-10-02",
    enOferta: false,
    precioAnterior: null
  },

  // ===== MITSUBISHI (5) =====
  {
    id: 35,
    marca: "Mitsubishi",
    modelo: "Outlander",
    ano: 2024,
    tipo: "SUV",
    precio: 2800000,
    precioConsultar: false,
    combustible: "Gasolina",
    transmision: "Automatica",
    kilometraje: 14000,
    color: "Blanco Diamante",
    imagenes: [
      "https://images.unsplash.com/photo-1559416523-140ddc3d238c?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1619405399517-d7fce0f13302?auto=format&fit=crop&w=800&q=80"
    ],
    destacado: true,
    condicion: "Usado",
    descripcion: "Outlander rediseñada con 7 asientos y la mejor relacion calidad-precio en SUV grande.",
    caracteristicas: ["Super All-Wheel Control", "7 asientos", "Pantalla 9 pulgadas", "MI-PILOT Assist", "10 anos de garantia"],
    fechaAgregado: "2026-02-18",
    enOferta: false,
    precioAnterior: null
  },
  {
    id: 36,
    marca: "Mitsubishi",
    modelo: "L200",
    ano: 2024,
    tipo: "Pickup",
    precio: 2550000,
    precioConsultar: false,
    combustible: "Diesel",
    transmision: "Automatica",
    kilometraje: 0,
    color: "Gris Titanio",
    imagenes: [
      "https://images.unsplash.com/photo-1629897048514-3dd7414fe72a?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1619767886558-efdc259cde1a?auto=format&fit=crop&w=800&q=80"
    ],
    destacado: false,
    condicion: "Nuevo",
    descripcion: "L200 nueva con motor turbo diesel de alto rendimiento, la pickup mas confiable.",
    caracteristicas: ["Motor diesel 2.4L MIVEC", "Super Select 4WD-II", "Caja automatica 6 velocidades", "Hill Descent Control", "Trailer Stability Assist"],
    fechaAgregado: "2026-03-22",
    enOferta: false,
    precioAnterior: null
  },
  {
    id: 37,
    marca: "Mitsubishi",
    modelo: "ASX",
    ano: 2023,
    tipo: "Crossover",
    precio: 1750000,
    precioConsultar: false,
    combustible: "Gasolina",
    transmision: "Automatica",
    kilometraje: 20000,
    color: "Rojo Rally",
    imagenes: [
      "https://images.unsplash.com/photo-1609521263047-f8f205293f24?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?auto=format&fit=crop&w=800&q=80"
    ],
    destacado: false,
    condicion: "Usado",
    descripcion: "ASX compacta con herencia rally, agil en la ciudad y capaz en carretera.",
    caracteristicas: ["Motor MIVEC 2.0L", "Pantalla multimedia", "Bluetooth y USB", "Control de crucero"],
    fechaAgregado: "2025-11-05",
    enOferta: false,
    precioAnterior: null
  },
  {
    id: 38,
    marca: "Mitsubishi",
    modelo: "Eclipse Cross",
    ano: 2024,
    tipo: "Crossover",
    precio: 2150000,
    precioConsultar: false,
    combustible: "Gasolina",
    transmision: "Automatica",
    kilometraje: 0,
    color: "Negro Cosmico",
    imagenes: [
      "https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1616422285623-13ff0162193c?auto=format&fit=crop&w=800&q=80"
    ],
    destacado: false,
    condicion: "Nuevo",
    descripcion: "Eclipse Cross con estilo coupe y tecnologia avanzada, destaca en cualquier lugar.",
    caracteristicas: ["Motor turbo 1.5L", "Sistema S-AWC", "Head-up display", "Pantalla tactil 8 pulgadas", "Techo panoramico"],
    fechaAgregado: "2026-01-30",
    enOferta: false,
    precioAnterior: null
  },
  {
    id: 39,
    marca: "Mitsubishi",
    modelo: "Montero Sport",
    ano: 2022,
    tipo: "SUV",
    precio: 3000000,
    precioConsultar: false,
    combustible: "Diesel",
    transmision: "Automatica",
    kilometraje: 60000,
    color: "Blanco Perla",
    imagenes: [
      "https://images.unsplash.com/photo-1617469767053-d3b523a0b982?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1550355291-bbee04a92027?auto=format&fit=crop&w=800&q=80"
    ],
    destacado: false,
    condicion: "Usado",
    descripcion: "Montero Sport diesel con capacidad todoterreno legendaria, ideal para el interior del pais.",
    caracteristicas: ["Motor diesel 2.4L turbo", "Super Select 4WD-II", "7 asientos", "Ultimas tecnologias de seguridad", "Diferencial trasero con bloqueo"],
    fechaAgregado: "2025-06-15",
    enOferta: false,
    precioAnterior: null
  },

  // ===== CHEVROLET (4) =====
  {
    id: 40,
    marca: "Chevrolet",
    modelo: "Tracker",
    ano: 2025,
    tipo: "Crossover",
    precio: 1850000,
    precioConsultar: false,
    combustible: "Gasolina",
    transmision: "Automatica",
    kilometraje: 0,
    color: "Azul Noche",
    imagenes: [
      "https://images.unsplash.com/photo-1583121274602-3e2820c69888?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1544636331-e26879cd4d9b?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=800&q=80"
    ],
    destacado: false,
    condicion: "Nuevo",
    descripcion: "Tracker nueva con motor turbo y conectividad total para el conductor moderno.",
    caracteristicas: ["Motor turbo 1.2L", "OnStar conectividad", "Pantalla tactil 8 pulgadas", "6 airbags", "Wi-Fi integrado"],
    fechaAgregado: "2026-03-05",
    enOferta: false,
    precioAnterior: null
  },
  {
    id: 41,
    marca: "Chevrolet",
    modelo: "Silverado",
    ano: 2022,
    tipo: "Pickup",
    precio: 3800000,
    precioConsultar: false,
    combustible: "Gasolina",
    transmision: "Automatica",
    kilometraje: 55000,
    color: "Negro",
    imagenes: [
      "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=800&q=80"
    ],
    destacado: false,
    condicion: "Usado",
    descripcion: "Silverado potente con motor V8, la pickup americana preferida en el Caribe.",
    caracteristicas: ["Motor V8 5.3L EcoTec3", "Transmision 10 velocidades", "Cama MultiPro", "Apple CarPlay y Android Auto", "Camara HD"],
    fechaAgregado: "2025-09-10",
    enOferta: false,
    precioAnterior: null
  },
  {
    id: 42,
    marca: "Chevrolet",
    modelo: "Onix",
    ano: 2024,
    tipo: "Sedan",
    precio: 1200000,
    precioConsultar: false,
    combustible: "Gasolina",
    transmision: "Automatica",
    kilometraje: 12000,
    color: "Blanco Summit",
    imagenes: [
      "https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1606016159991-dfe4f2746ad5?auto=format&fit=crop&w=800&q=80"
    ],
    destacado: false,
    condicion: "Usado",
    descripcion: "Onix turbo con gran eficiencia y bajo costo operativo, lider en su segmento.",
    caracteristicas: ["Motor turbo 1.0L", "MyLink con pantalla 8 pulgadas", "OnStar", "Alerta de colision frontal"],
    fechaAgregado: "2026-01-15",
    enOferta: false,
    precioAnterior: null
  },
  {
    id: 43,
    marca: "Chevrolet",
    modelo: "Equinox",
    ano: 2024,
    tipo: "SUV",
    precio: 2600000,
    precioConsultar: false,
    combustible: "Gasolina",
    transmision: "Automatica",
    kilometraje: 0,
    color: "Gris Acero",
    imagenes: [
      "https://images.unsplash.com/photo-1559416523-140ddc3d238c?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1619405399517-d7fce0f13302?auto=format&fit=crop&w=800&q=80"
    ],
    destacado: false,
    condicion: "Nuevo",
    descripcion: "Equinox nueva generacion con mas espacio y la tecnologia Chevrolet Safety Assist.",
    caracteristicas: ["Motor turbo 1.5L", "Chevy Safety Assist", "Pantalla diagonal 11 pulgadas", "Wireless CarPlay y Android Auto", "Traccion AWD disponible"],
    fechaAgregado: "2026-02-25",
    enOferta: false,
    precioAnterior: null
  },

  // ===== SUZUKI (3) =====
  {
    id: 44,
    marca: "Suzuki",
    modelo: "Vitara",
    ano: 2024,
    tipo: "Crossover",
    precio: 1950000,
    precioConsultar: false,
    combustible: "Gasolina",
    transmision: "Automatica",
    kilometraje: 8000,
    color: "Turquesa",
    imagenes: [
      "https://images.unsplash.com/photo-1629897048514-3dd7414fe72a?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1619767886558-efdc259cde1a?auto=format&fit=crop&w=800&q=80"
    ],
    destacado: false,
    condicion: "Usado",
    descripcion: "Vitara con sistema AllGrip y diseno bicolor, compacta pero con espiritu aventurero.",
    caracteristicas: ["Sistema AllGrip AWD", "Techo bicolor", "Pantalla tactil 9 pulgadas", "Suzuki Connect"],
    fechaAgregado: "2026-02-12",
    enOferta: false,
    precioAnterior: null
  },
  {
    id: 45,
    marca: "Suzuki",
    modelo: "Swift",
    ano: 2024,
    tipo: "Sedan",
    precio: 1100000,
    precioConsultar: false,
    combustible: "Gasolina",
    transmision: "Automatica",
    kilometraje: 0,
    color: "Amarillo Champion",
    imagenes: [
      "https://images.unsplash.com/photo-1609521263047-f8f205293f24?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?auto=format&fit=crop&w=800&q=80"
    ],
    destacado: false,
    condicion: "Nuevo",
    descripcion: "Swift divertido de manejar con motor eficiente, el hatchback mas agil del mercado.",
    caracteristicas: ["Motor DualJet 1.2L", "Plataforma HEARTECT", "Peso ligero", "Pantalla multimedia"],
    fechaAgregado: "2026-03-14",
    enOferta: true,
    precioAnterior: 1250000
  },
  {
    id: 46,
    marca: "Suzuki",
    modelo: "Jimny",
    ano: 2024,
    tipo: "SUV",
    precio: 2200000,
    precioConsultar: false,
    combustible: "Gasolina",
    transmision: "Automatica",
    kilometraje: 0,
    color: "Verde Jungla",
    imagenes: [
      "https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1616422285623-13ff0162193c?auto=format&fit=crop&w=800&q=80"
    ],
    destacado: true,
    condicion: "Nuevo",
    descripcion: "Jimny iconico con capacidad 4x4 profesional en un formato compacto y divertido.",
    caracteristicas: ["ALLGRIP PRO 4x4", "Chasis de escalera", "Angulos de ataque y salida amplios", "Diseno retro moderno", "Hill Hold y Descent Control"],
    fechaAgregado: "2026-03-26",
    enOferta: false,
    precioAnterior: null
  },

  // ===== MAZDA (3) =====
  {
    id: 47,
    marca: "Mazda",
    modelo: "CX-5",
    ano: 2024,
    tipo: "SUV",
    precio: 2650000,
    precioConsultar: false,
    combustible: "Gasolina",
    transmision: "Automatica",
    kilometraje: 16000,
    color: "Rojo Soul Crystal",
    imagenes: [
      "https://images.unsplash.com/photo-1617469767053-d3b523a0b982?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1550355291-bbee04a92027?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1583121274602-3e2820c69888?auto=format&fit=crop&w=800&q=80"
    ],
    destacado: false,
    condicion: "Usado",
    descripcion: "CX-5 con el premiado diseno Kodo y dinamica de manejo superior en su clase.",
    caracteristicas: ["Motor SKYACTIV-G 2.5L", "i-ACTIVSENSE", "Interior en cuero Nappa", "Bose 10 parlantes", "Head-up display"],
    fechaAgregado: "2026-01-22",
    enOferta: false,
    precioAnterior: null
  },
  {
    id: 48,
    marca: "Mazda",
    modelo: "Mazda3",
    ano: 2023,
    tipo: "Sedan",
    precio: 1650000,
    precioConsultar: false,
    combustible: "Gasolina",
    transmision: "Automatica",
    kilometraje: 25000,
    color: "Gris Machine",
    imagenes: [
      "https://images.unsplash.com/photo-1544636331-e26879cd4d9b?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=800&q=80"
    ],
    destacado: false,
    condicion: "Usado",
    descripcion: "Mazda3 con acabados premium que compiten con marcas de lujo, placer de conducir.",
    caracteristicas: ["Motor SKYACTIV-G 2.0L", "Mazda Connect 8.8 pulgadas", "G-Vectoring Control Plus", "Camara de reversa"],
    fechaAgregado: "2025-12-10",
    enOferta: false,
    precioAnterior: null
  },
  {
    id: 49,
    marca: "Mazda",
    modelo: "CX-30",
    ano: 2025,
    tipo: "Crossover",
    precio: 2100000,
    precioConsultar: false,
    combustible: "Gasolina",
    transmision: "Automatica",
    kilometraje: 0,
    color: "Blanco Artico",
    imagenes: [
      "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1580273916550-e323be2ae537?auto=format&fit=crop&w=800&q=80"
    ],
    destacado: false,
    condicion: "Nuevo",
    descripcion: "CX-30 que fusiona la elegancia de un sedan con la versatilidad de un crossover.",
    caracteristicas: ["Motor SKYACTIV-G 2.5L", "i-ACTIV AWD", "Pantalla 8.8 pulgadas", "Off-Road Traction Assist", "Wireless Apple CarPlay"],
    fechaAgregado: "2026-03-19",
    enOferta: false,
    precioAnterior: null
  },

  // ===== FORD (3) =====
  {
    id: 50,
    marca: "Ford",
    modelo: "Explorer",
    ano: 2023,
    tipo: "SUV",
    precio: 3750000,
    precioConsultar: false,
    combustible: "Gasolina",
    transmision: "Automatica",
    kilometraje: 42000,
    color: "Negro Agate",
    imagenes: [
      "https://images.unsplash.com/photo-1606016159991-dfe4f2746ad5?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1559416523-140ddc3d238c?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?auto=format&fit=crop&w=800&q=80"
    ],
    destacado: false,
    condicion: "Usado",
    descripcion: "Explorer con motor EcoBoost potente y espacio para 7 pasajeros con total confort.",
    caracteristicas: ["Motor EcoBoost V6 twin-turbo", "7 asientos", "Ford Co-Pilot360", "SYNC 4 con pantalla 10.1 pulgadas", "Traccion inteligente AWD"],
    fechaAgregado: "2025-11-20",
    enOferta: false,
    precioAnterior: null
  },
  {
    id: 51,
    marca: "Ford",
    modelo: "Ranger",
    ano: 2024,
    tipo: "Pickup",
    precio: 2850000,
    precioConsultar: false,
    combustible: "Diesel",
    transmision: "Automatica",
    kilometraje: 18000,
    color: "Azul Relámpago",
    imagenes: [
      "https://images.unsplash.com/photo-1619405399517-d7fce0f13302?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1629897048514-3dd7414fe72a?auto=format&fit=crop&w=800&q=80"
    ],
    destacado: false,
    condicion: "Usado",
    descripcion: "Ranger disenada para conquistar cualquier terreno dominicano con potencia y estilo.",
    caracteristicas: ["Motor diesel biturbo 2.0L", "Transmision 10 velocidades", "Traccion 4x4 electronica", "SYNC 4A con pantalla 12 pulgadas", "Zone Body Lighting"],
    fechaAgregado: "2026-02-08",
    enOferta: false,
    precioAnterior: null
  },
  {
    id: 52,
    marca: "Ford",
    modelo: "Escape",
    ano: 2024,
    tipo: "SUV",
    precio: 2300000,
    precioConsultar: false,
    combustible: "Hibrido",
    transmision: "Automatica",
    kilometraje: 0,
    color: "Plata Iconic",
    imagenes: [
      "https://images.unsplash.com/photo-1619767886558-efdc259cde1a?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1609521263047-f8f205293f24?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?auto=format&fit=crop&w=800&q=80"
    ],
    destacado: false,
    condicion: "Nuevo",
    descripcion: "Escape hibrida con excelente economia de combustible y la versatilidad que necesitas.",
    caracteristicas: ["Motor hibrido 2.5L", "Ford Co-Pilot360 Assist+", "Pantalla 13.2 pulgadas", "Modo EV", "Portaequipaje manos libres"],
    fechaAgregado: "2026-03-24",
    enOferta: false,
    precioAnterior: null
  }
];

// ===== CONSTANTES DE FILTRADO =====
const MARCAS_DISPONIBLES = [...new Set(VEHICULOS.map(v => v.marca))].sort();
const TIPOS_DISPONIBLES = [...new Set(VEHICULOS.map(v => v.tipo))].sort();
const ANOS_DISPONIBLES = [...new Set(VEHICULOS.map(v => v.ano))].sort((a, b) => b - a);
const COMBUSTIBLES_DISPONIBLES = [...new Set(VEHICULOS.map(v => v.combustible))].sort();
